

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import SliderBar from "@/components/SlideBar";
import MyApp from '@/components/LearningDoc/添加交互/06 更新state中的数组/index'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className} >
              <div className="flex w-full h-full">
                  <SliderBar  />
                  <div className="border border-indigo-600 w-full h-full">
                    <MyApp />
                  </div>
                  
                {/* <div className="w-full h-full">{children}</div> */}
            </div>
         </body>
    </html>
  );
}
